# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8888
    #context-path: /renren-fast  #与common.js baseURL对应方能在tomcat下正确运行
    context-path: /
    
# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: pro
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
        max-file-size: 100MB
        max-request-size: 100MB
        enabled: true
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml

#http:
#  multipart:
#    enabled:true
#    max-file-size:3MB
#    max-request-size:3MB 

